### ISSUE TITLE
Debugging...

### ISSUE THREAD

**Issue by logopk** [coreruleset/antivirus-plugin#2]
Hi,

I have tried to set it up, but apparently it's not scanning. I don't know if that is a problem in the plugin or the connection to clamd (which is in a remote docker container - i have changed the settings to tcp).

Any hints how to get more visibility?

Peter

**Comment by azurit** [comment]
@logopk How's your digging? Have you found something?

**Comment by azurit** [comment]
Is everything ok now? Can we close this issue?

**Comment by logopk** [comment]
Yes Thanks!
(I promise to RTFM next time :-) )
